import { useState } from "react";

const C = {
  bg: "#0B1120", surface: "#131B2E", border: "#1E293B",
  text: "#E2E8F0", textDim: "#94A3B8", accent: "#3B82F6",
  green: "#22C55E", red: "#EF4444", yellow: "#EAB308",
};

const PILLARS = [
  {
    id: "monitoring",
    icon: "◉",
    title: "Monitoring",
    subtitle: "Know what the model decided",
    color: C.accent,
    principles: [
      "Log every LLM call with full prompt, response, and token-level grounding classification",
      "Track grounding ratios per agent step — confabulation rate is your primary quality metric",
      "Alert on dimension resolution drops — when density falls below threshold, output quality degrades",
      "Record decision traces: which constraint drove each architectural choice in the output",
    ],
    antipatterns: [
      "Treating LLM output as a black box — 'it works' is not monitoring",
      "Only logging errors — confabulation often looks correct but is ungrounded",
      "Sampling responses instead of tracing every call — drift happens at the margins",
    ],
    examples: [
      {
        title: "Token Grounding Dashboard",
        desc: "Real-time display of grounded/inferred/defaulted/confabulated ratios per agent step. Confabulation spike from 2% to 15% triggers investigation — found that a prompt template change removed three constraint tokens.",
      },
      {
        title: "Decision Audit Trail",
        desc: "For a deployment pipeline agent: 'chose us-east-1 (constraint: region=us-east-1, grounded), chose t3.large (no constraint, defaulted from training data)'. The defaulted decision is a hallucination vector caught before production.",
      },
    ],
  },
  {
    id: "configurability",
    icon: "⚙",
    title: "Configurability",
    subtitle: "Change behavior without retraining",
    color: C.green,
    principles: [
      "Externalize all constraint tokens — channel resolution states should be configuration, not code",
      "Spec-driven prompts: the Dense Architecture Specification IS the config file",
      "Version specifications alongside code — git diff on the spec shows exactly what changed in model behavior",
      "Support hot-reload of constraint configurations without redeployment",
    ],
    antipatterns: [
      "Hardcoding prompts in application code — makes behavior changes require deploys",
      "Using model fine-tuning when prompt engineering suffices — fine-tuning is expensive and opaque",
      "Mixing business logic with prompt construction — separation of concerns applies to AI too",
    ],
    examples: [
      {
        title: "Spec-as-Config",
        desc: "The Dense Architecture Specification generated by the agent becomes a YAML/JSON config. Changing 'Database: PostgreSQL' to 'Database: MySQL' and re-running produces correctly adapted code — no prompt engineering required.",
      },
      {
        title: "Channel Override",
        desc: "Production issue: auth middleware needs to change from JWT to session-based. Update the auth channel constraints, regenerate spec, re-run code generation. The change is traceable, reviewable, and deterministic.",
      },
    ],
  },
  {
    id: "predictability",
    icon: "◫",
    title: "Predictability",
    subtitle: "Same input, same output — always",
    color: C.yellow,
    principles: [
      "Maximize density to minimize stochastic variance — resolved dimensions can't vary",
      "Use temperature 0 with dense specs — when all dimensions are resolved, sampling doesn't matter",
      "Test with N-run consistency checks: if output varies across runs, you have unresolved dimensions",
      "Pin model versions — same spec + same model = deterministic output",
    ],
    antipatterns: [
      "Relying on high temperature for 'creativity' — creativity = confabulation when dimensions are unresolved",
      "Testing with a single run — consistency requires multiple executions",
      "Assuming reproducibility without verification — always run the consistency check",
    ],
    examples: [
      {
        title: "5-Run Consistency Gate",
        desc: "CI pipeline runs the same spec through the LLM 5 times. If Jaccard similarity of architectural decisions drops below 95%, the pipeline fails. Forces teams to resolve dimensions before merging.",
      },
      {
        title: "Drift Detection",
        desc: "Weekly job generates code from the current spec and compares against the previous week's output. Any delta indicates either a spec change (intended) or model drift (investigate). Catches model updates that silently change default behavior.",
      },
    ],
  },
];

export default function AgenticSystems() {
  const [expanded, setExpanded] = useState("monitoring");
  const [tab, setTab] = useState("principles");

  const pillar = PILLARS.find(p => p.id === expanded);

  return (
    <div style={{ padding: "20px 30px", maxWidth: 1000, margin: "0 auto" }}>
      <h2 style={{ color: C.text, fontSize: 24, marginBottom: 4 }}>Three Pillars of Stable Agentic Systems</h2>
      <p style={{ color: C.textDim, fontSize: 14, marginBottom: 24 }}>
        Click a pillar to explore its principles, anti-patterns, and examples
      </p>

      {/* Pillar cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginBottom: 24 }}>
        {PILLARS.map(p => (
          <div key={p.id} onClick={() => { setExpanded(p.id); setTab("principles"); }}
            style={{
              background: expanded === p.id ? `${p.color}15` : C.surface,
              border: `1px solid ${expanded === p.id ? p.color : C.border}`,
              borderRadius: 8, padding: "20px", cursor: "pointer",
              transition: "all 0.2s", textAlign: "center",
            }}>
            <div style={{ fontSize: 32, marginBottom: 8 }}>{p.icon}</div>
            <div style={{ color: p.color, fontSize: 18, fontWeight: 700, marginBottom: 4 }}>{p.title}</div>
            <div style={{ color: C.textDim, fontSize: 13 }}>{p.subtitle}</div>
          </div>
        ))}
      </div>

      {/* Detail panel */}
      {pillar && (
        <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8 }}>
          {/* Tabs */}
          <div style={{ display: "flex", borderBottom: `1px solid ${C.border}` }}>
            {["principles", "antipatterns", "examples"].map(t => (
              <button key={t} onClick={() => setTab(t)}
                style={{
                  flex: 1, padding: "12px", background: "none",
                  border: "none", borderBottom: tab === t ? `2px solid ${pillar.color}` : "2px solid transparent",
                  color: tab === t ? pillar.color : C.textDim,
                  cursor: "pointer", fontSize: 13, fontWeight: 600,
                }}>
                {t === "antipatterns" ? "Anti-Patterns" : t.charAt(0).toUpperCase() + t.slice(1)}
              </button>
            ))}
          </div>

          <div style={{ padding: "20px" }}>
            {tab === "principles" && (
              <ul style={{ margin: 0, padding: "0 0 0 20px" }}>
                {pillar.principles.map((p, i) => (
                  <li key={i} style={{ color: C.text, fontSize: 14, lineHeight: 1.6, marginBottom: 10 }}>
                    {p}
                  </li>
                ))}
              </ul>
            )}

            {tab === "antipatterns" && (
              <ul style={{ margin: 0, padding: "0 0 0 20px" }}>
                {pillar.antipatterns.map((p, i) => (
                  <li key={i} style={{ color: C.red, fontSize: 14, lineHeight: 1.6, marginBottom: 10 }}>
                    {p}
                  </li>
                ))}
              </ul>
            )}

            {tab === "examples" && (
              <div>
                {pillar.examples.map((ex, i) => (
                  <div key={i} style={{ marginBottom: 16, padding: "12px 16px",
                    background: `${pillar.color}08`, border: `1px solid ${pillar.color}22`,
                    borderRadius: 6 }}>
                    <h4 style={{ color: pillar.color, margin: "0 0 6px", fontSize: 14 }}>{ex.title}</h4>
                    <p style={{ color: C.textDim, margin: 0, fontSize: 13, lineHeight: 1.5 }}>{ex.desc}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
