// All 24 slides for Module 3. Each text slide has id + type + title + {subtitle | body | bullets | keyTakeaway}.
// Each component slide has id + type: "component" + component (string key) + instructions.
// Each assessment slide has id + type: "assessment".
export const SLIDES = [
  {
    id: 'title',
    type: 'text',
    title: 'Context & Sessions: The Hidden Mechanic',
    subtitle: 'Why your 200k-token context is lying to you',
    body: 'You already know how attention works (Module 1) and how to write dense prompts (Module 2). This module shows the hidden mechanic that decides whether either one actually helps: where your information sits in the context, and how sessions accumulate noise.',
  },
  {
    id: 'agenda',
    type: 'text',
    title: "What We'll Cover",
    bullets: [
      { label: 'The Hook', desc: 'Advertised context length vs. effective context length' },
      { label: 'Lost-in-the-Middle', desc: 'Liu et al. 2023 and the U-curve' },
      { label: 'Why It Happens', desc: 'Attention budget revisited in long contexts' },
      { label: 'Context ≠ Prompt', desc: 'Everything that competes for attention mass' },
      { label: 'Two Levers', desc: 'Prompt engineering vs. context engineering' },
      { label: 'Governance Surface', desc: 'Context as a compliance and policy concern' },
      { label: 'Session Hygiene', desc: 'Six practices + nuclear restart' },
      { label: 'Worked Example', desc: 'A messy session vs. a hygienic one' },
      { label: 'Assessment', desc: '15 MCQ + 4 diagnostic scenarios' },
    ],
  },
  {
    id: 'hook',
    type: 'text',
    title: "You've Been Lied to About Context Length",
    subtitle: '200k tokens advertised. ~40k tokens effective. That gap is where bugs live.',
    body: 'Providers quote context length as a hard cap: "up to 200k tokens." In practice, recall accuracy on a single fact buried deep in that context starts degrading well before the cap. A constraint placed at token 100,000 in a 200k context is often forgotten by the time the model answers.',
    keyTakeaway: 'Advertised context length is a maximum, not a guarantee. Effective context is where recall stays above a usable threshold.',
  },
  {
    id: 'lost-in-middle-intro',
    type: 'text',
    title: 'Lost-in-the-Middle',
    subtitle: 'Liu et al. 2023 — "Lost in the Middle: How Language Models Use Long Contexts"',
    body: 'The finding: when a single relevant fact is placed at varying positions in a long input, models recall it reliably when it sits near the start (primacy) or near the end (recency), but accuracy drops sharply when it sits in the middle. The result is a U-shaped curve, and it holds across model sizes and architectures.',
    keyTakeaway: 'Attention is not uniform across the context window. The middle is darker than the ends.',
  },
  {
    id: 'lost-in-middle-demo',
    type: 'component',
    component: 'LostInTheMiddleCurve',
    instructions: 'Drag the needle to any position. Adjust context length and noise. Watch the U-curve, then rotate the 3D surface to see how position × context length jointly shape recall.',
  },
  {
    id: 'why-it-happens',
    type: 'text',
    title: 'Why It Happens',
    subtitle: 'Attention dilution, revisited at scale',
    body: 'Module 1 showed softmax distributing probability mass across every token in the context. In a 200k-token context, every additional token steals a tiny slice of attention. Combine that with positional encodings that give stronger signal at sequence ends, and the middle becomes a relative desert. There is nothing special about the middle in the training data — the architecture itself produces the U-curve.',
    keyTakeaway: 'The U-curve is a structural property of transformer attention over long sequences. Not a bug — a budget problem.',
  },
  {
    id: 'effective-vs-advertised',
    type: 'text',
    title: 'Effective vs. Advertised Context',
    subtitle: 'Where does recall actually hold?',
    body: 'A useful rule of thumb: effective context for high-stakes retrieval is often 20–40% of advertised. GPT-4 Turbo at 128k advertised holds well to ~40k. Claude Sonnet at 200k holds better (historically to ~80k+), but still degrades. Smaller or older "long-context" models may effectively be half their advertised number.',
    keyTakeaway: 'Design for the effective length you can verify, not the number on the tin.',
  },
  {
    id: 'playground',
    type: 'component',
    component: 'ContextWindowPlayground',
    instructions: 'Place a needle anywhere in the context. Drag the window-size slider from 1k to 200k. Watch the landscape flatten and the middle recall collapse. Try different model presets.',
  },
  {
    id: 'context-vs-prompt',
    type: 'text',
    title: 'Context ≠ Prompt',
    subtitle: 'Your prompt is the tip of a much larger iceberg',
    body: '"Prompt" is the text you type this turn. "Context" is everything the model sees: system prompt, every prior turn, every tool call and its output, every attached file, retrieved documents, and finally — your current prompt. Every byte of that competes for the same attention budget.',
    keyTakeaway: 'Whenever someone says "just a prompt," ask what else is in the window.',
  },
  {
    id: 'anatomy',
    type: 'text',
    title: 'Anatomy of the Window',
    bullets: [
      { label: 'System prompt', desc: 'Persistent instructions; high-attention real estate at the start' },
      { label: 'Chat history', desc: 'Every prior user + assistant turn, in order' },
      { label: 'Tool outputs', desc: 'File reads, search results, API responses — often huge' },
      { label: 'Attachments', desc: 'Uploaded files, images, PDFs — tokenized inline' },
      { label: 'RAG / retrieved docs', desc: 'Any chunks you pre-pended for this turn' },
      { label: 'User turn', desc: 'What you actually typed — usually the smallest slice' },
    ],
    keyTakeaway: 'The user turn is often the smallest fraction of what the model reads.',
  },
  {
    id: 'anatomy-3d',
    type: 'component',
    component: 'ContextAnatomyBars3D',
    instructions: 'Same session, four moments in time. The gold bar = a constraint placed at turn 1. Watch its share of the context window collapse from 60% to 1% as history, tool outputs, and attachments accumulate. Click any column header to isolate it.',
  },
  {
    id: 'budget-intro',
    type: 'text',
    title: 'Context as a Budget',
    subtitle: '100% attention mass. You have to allocate it.',
    body: 'If attention were infinite, you could dump everything and let the model sort it out. It is not infinite. Softmax guarantees the sum across all positions is exactly 1. Every chunk of context you add dilutes the share available to every other chunk.',
    keyTakeaway: 'Every token you include is a vote against every other token.',
  },
  {
    id: 'budget-demo',
    type: 'component',
    component: 'AttentionBudgetAllocator',
    instructions: 'Add chunks of different types and sizes. Watch the budget redistribute. Try to keep "attention per critical token" above 5%.',
  },
  {
    id: 'two-levers',
    type: 'text',
    title: 'The Two Levers',
    subtitle: 'Prompt engineering and context engineering are not in competition',
    body: 'Prompt engineering shapes the current turn — structure, role, constraints, examples, format. Context engineering shapes what else is in the window — what you include, what you exclude, what order, and what gets summarized. Both act on the same attention mechanism. Used together, they compound. Used alone, each hits a ceiling.',
    keyTakeaway: 'Prompt engineering makes each token count. Context engineering decides which tokens get to compete in the first place.',
  },
  {
    id: 'prompt-engineering-six',
    type: 'text',
    title: 'Prompt Engineering: Six Techniques',
    bullets: [
      { label: 'XML structure', desc: '<constraints>, <examples>, <instructions> — unambiguous sections' },
      { label: 'Role prime', desc: '"You are a senior security engineer…" — activates domain priors' },
      { label: 'Explicit constraints', desc: 'Hard rules stated as "MUST" and "MUST NOT"' },
      { label: 'Few-shot examples', desc: 'Concrete input→output pairs the model can pattern-match' },
      { label: 'Chain-of-thought', desc: '"Think step by step" or structured reasoning scaffolding' },
      { label: 'Output format spec', desc: 'Tight schema (JSON, table, fields) the model must match' },
    ],
  },
  {
    id: 'context-engineering-six',
    type: 'text',
    title: 'Context Engineering: Six Techniques',
    bullets: [
      { label: 'Front/tail-load critical', desc: 'Put constraints where attention is strongest: start and end' },
      { label: 'Summarize old turns', desc: 'Compress aged history; drop verbatim turns' },
      { label: 'Pin invariants', desc: 'Periodically re-assert constraints so they live in the recency window' },
      { label: 'Prune tool outputs', desc: 'Keep the excerpt you need, not the whole file' },
      { label: 'Scope sessions', desc: 'One concern per session; start fresh for new concerns' },
      { label: 'External memory', desc: 'Scratchpad files, indexed specs, policy docs — fetched on demand' },
    ],
  },
  {
    id: 'lever-demo',
    type: 'component',
    component: 'LeverComparisonTool',
    instructions: 'Same task, two panes. Toggle prompt levers (left) and context levers (right) and watch the score. Try "Match the other side" to push one lever as far as it will go.',
  },
  {
    id: 'governance',
    type: 'text',
    title: 'Context as Governance Surface',
    subtitle: "What goes into the window is not just an engineering decision — it's a policy decision",
    body: 'If your context includes PII, confidential customer data, or proprietary source code, the model sees it. Any downstream logging, any cache, any training pipeline sees it too. Context composition is therefore a compliance boundary. Organizations that treat it as one install guardrails on inputs (what data is allowed in), enforce attached indices (company API specs, policy docs), and audit what actually reached the model.',
    keyTakeaway: 'Every LLM invocation is a data-egress event. Context is the boundary.',
  },
  {
    id: 'external-memory',
    type: 'text',
    title: 'External Memory, Indices, and Guardrails',
    bullets: [
      { label: 'PII / confidential filters', desc: 'Strip sensitive fields before context assembly; policy-enforced' },
      { label: 'API spec index', desc: 'Pull canonical API specs on demand — one source of truth, not N reinvented wheels' },
      { label: 'Policy / compliance index', desc: 'Retrieve the rules that must bind a design; cite them explicitly' },
      { label: 'Scratchpad files', desc: 'Persist reasoning across sessions (e.g., MEMORY.md) without paying context tax' },
      { label: 'Outbound validators', desc: 'Screen model output before it acts on shared systems' },
    ],
    keyTakeaway: 'External memory earns its keep when it replaces a larger chunk of context than it adds.',
  },
  {
    id: 'hygiene-intro',
    type: 'text',
    title: 'Session Hygiene: Six Practices + Nuclear Restart',
    subtitle: 'The playbook for keeping long sessions useful',
    bullets: [
      { label: '1. Front/tail-load', desc: 'Critical constraints at start AND end — never stuck in the middle' },
      { label: '2. Summarize', desc: 'Compress aged turns; strip noise; keep the decisions' },
      { label: '3. Pin invariants', desc: 'Re-state hard rules periodically so they stay in recency' },
      { label: '4. Prune tool outputs', desc: 'Keep excerpts; drop raw dumps after the relevant bit is extracted' },
      { label: '5. Scope', desc: 'One concern per session; fork for new concerns' },
      { label: '6. Watch effective length', desc: "Don't trust the advertised number; watch for degradation" },
      { label: 'Nuclear restart', desc: 'When none of the above works: summarize, then start fresh' },
    ],
  },
  {
    id: 'simulator',
    type: 'component',
    component: 'SessionHygieneSimulator',
    instructions: 'This session has a critical fact at turn 2, then accumulates noise. Toggle interventions to get recall on the turn-2 fact above 90%.',
  },
  {
    id: 'worked-example',
    type: 'text',
    title: 'Worked Example: Before & After',
    subtitle: 'A real messy session vs. a hygienic one',
    body: 'On the left: a 30-turn session covering three different concerns, with four raw file dumps, no summarization, and a key constraint placed at turn 3 and never restated. On the right: the same work split into scoped sessions, with summaries, pinned invariants, and tool outputs pruned to excerpts. The hygienic session is half the tokens and delivers correct output on the first try.',
    keyTakeaway: "The cost of hygiene is small. The cost of skipping it is everything the model didn't catch.",
  },
  {
    id: 'assessment',
    type: 'assessment',
    instructions: '15 MCQ + 4 diagnostic scenarios. Pass threshold: 80% overall AND 75% on diagnostics.',
  },
  {
    id: 'recap',
    type: 'text',
    title: 'Recap & Bridge to Module 4',
    subtitle: 'You now have the hidden mechanic',
    body: 'Module 4 (Building with LLMs) relies on every practice here. Decomposition, orchestration, parallel agent dispatch — all of it fails without context hygiene. An orchestrator that dumps every sub-agent\'s full output into the parent context will lose the middle every time.',
    keyTakeaway: 'Context hygiene is the prerequisite for every agentic system.',
  },
]
