// All 24 slides for Module 3. Each text slide has id + type + title + {subtitle | body | bullets | keyTakeaway}.
// Each component slide has id + type: "component" + component (string key) + instructions.
// Each assessment slide has id + type: "assessment".
export const SLIDES = [
  {
    id: 'title',
    type: 'text',
    title: 'Context & Sessions: The Hidden Mechanic',
    subtitle: 'Why your 200k-token context is lying to you',
    body: 'You already know how attention works (Module 1) and how to write dense prompts (Module 2). This module shows the hidden mechanic that decides whether either one actually helps: where your information sits in the context, and how sessions accumulate noise.',
  },
  {
    id: 'agenda',
    type: 'text',
    title: "What We'll Cover",
    bullets: [
      { label: 'The Hook', desc: 'Advertised context length vs. effective context length' },
      { label: 'Lost-in-the-Middle', desc: 'Liu et al. 2023 and the U-curve, live on the 3D surface' },
      { label: 'Attention Budget', desc: 'Anatomy of the window; why the middle decays at scale' },
      { label: 'Two Levers', desc: 'Prompt engineering vs. context engineering — same mechanism' },
      { label: 'Decomposition', desc: 'From dense spec to a wave plan of scoped agents' },
      { label: 'Agent Sessions', desc: 'Small, scoped, guarded, tested, sealed' },
      { label: 'Tools & RAG', desc: "Externalize what's common; govern inbound context" },
      { label: 'Vibe vs. Engineered', desc: 'Output quality diverges as complexity grows' },
      { label: 'Stacks vs. Towers', desc: '3D constraint-decay: five short stacks vs. one skyscraper' },
      { label: 'The Playbook', desc: 'Ten best practices with concrete before/after examples' },
      { label: 'Assessment & Take-Home', desc: '15 questions + the build_framework.md starter' },
    ],
  },
  {
    id: 'hook',
    type: 'text',
    title: "You've Been Lied to About Context Length",
    subtitle: '200k tokens advertised. ~40k tokens effective. That gap is where bugs live.',
    body: 'Providers quote context length as a hard cap: "up to 200k tokens." In practice, recall accuracy on a single fact buried deep in that context starts degrading well before the cap. A constraint placed at token 100,000 in a 200k context is often forgotten by the time the model answers.',
    keyTakeaway: 'Advertised context length is a maximum, not a guarantee. Effective context is where recall stays above a usable threshold.',
  },
  {
    id: 'lost-in-middle-intro',
    type: 'text',
    title: 'Lost-in-the-Middle',
    subtitle: 'Liu et al. 2023 — "Lost in the Middle: How Language Models Use Long Contexts"',
    body: 'The finding: when a single relevant fact is placed at varying positions in a long input, models recall it reliably when it sits near the start (primacy) or near the end (recency), but accuracy drops sharply when it sits in the middle. The result is a U-shaped curve, and it holds across model sizes and architectures.',
    keyTakeaway: 'Attention is not uniform across the context window. The middle is darker than the ends.',
  },
  {
    id: 'lost-in-middle-demo',
    type: 'component',
    component: 'LostInTheMiddleCurve',
    instructions: 'Drag the needle to any position. Adjust context length and noise. Watch the U-curve, then rotate the 3D surface to see how position × context length jointly shape recall.',
  },
  {
    id: 'why-it-happens',
    type: 'text',
    title: 'Why It Happens',
    subtitle: 'Attention dilution, revisited at scale',
    body: 'Module 1 showed softmax distributing probability mass across every token in the context. In a 200k-token context, every additional token steals a tiny slice of attention. Combine that with positional encodings that give stronger signal at sequence ends, and the middle becomes a relative desert. There is nothing special about the middle in the training data — the architecture itself produces the U-curve.',
    keyTakeaway: 'The U-curve is a structural property of transformer attention over long sequences. Not a bug — a budget problem.',
  },
  {
    id: 'effective-vs-advertised',
    type: 'text',
    title: 'Effective vs. Advertised Context',
    subtitle: 'Where does recall actually hold?',
    body: 'A useful rule of thumb: effective context for high-stakes retrieval is often 20–40% of advertised. GPT-4 Turbo at 128k advertised holds well to ~40k. Claude Sonnet at 200k holds better (historically to ~80k+), but still degrades. Smaller or older "long-context" models may effectively be half their advertised number.',
    keyTakeaway: 'Design for the effective length you can verify, not the number on the tin.',
  },
  {
    id: 'playground',
    type: 'component',
    component: 'ContextWindowPlayground',
    instructions: 'Place a needle anywhere in the context. Drag the window-size slider from 1k to 200k. Watch the landscape flatten and the middle recall collapse. Try different model presets.',
  },
  {
    id: 'context-vs-prompt',
    type: 'text',
    title: 'Context ≠ Prompt',
    subtitle: 'Your prompt is the tip of a much larger iceberg',
    body: '"Prompt" is the text you type this turn. "Context" is everything the model sees: system prompt, every prior turn, every tool call and its output, every attached file, retrieved documents, and finally — your current prompt. Every byte of that competes for the same attention budget.',
    keyTakeaway: 'Whenever someone says "just a prompt," ask what else is in the window.',
  },
  {
    id: 'anatomy',
    type: 'text',
    title: 'Anatomy of the Window',
    bullets: [
      { label: 'System prompt', desc: 'Persistent instructions; high-attention real estate at the start' },
      { label: 'Chat history', desc: 'Every prior user + assistant turn, in order' },
      { label: 'Tool outputs', desc: 'File reads, search results, API responses — often huge' },
      { label: 'Attachments', desc: 'Uploaded files, images, PDFs — tokenized inline' },
      { label: 'RAG / retrieved docs', desc: 'Any chunks you pre-pended for this turn' },
      { label: 'User turn', desc: 'What you actually typed — usually the smallest slice' },
    ],
    keyTakeaway: 'The user turn is often the smallest fraction of what the model reads.',
  },
  {
    id: 'anatomy-3d',
    type: 'component',
    component: 'ContextAnatomyBars3D',
    instructions: 'Same session, four moments in time. The gold bar = a constraint placed at turn 1. Watch its share of the context window collapse from 60% to 1% as history, tool outputs, and attachments accumulate. Click any column header to isolate it.',
  },
  {
    id: 'budget-intro',
    type: 'text',
    title: 'Context as a Budget',
    subtitle: '100% attention mass. You have to allocate it.',
    body: 'If attention were infinite, you could dump everything and let the model sort it out. It is not infinite. Softmax guarantees the sum across all positions is exactly 1. Every chunk of context you add dilutes the share available to every other chunk.',
    keyTakeaway: 'Every token you include is a vote against every other token.',
  },
  {
    id: 'budget-demo',
    type: 'component',
    component: 'AttentionBudgetAllocator',
    instructions: 'Add chunks of different types and sizes. Watch the budget redistribute. Try to keep "attention per critical token" above 5%.',
  },
  {
    id: 'two-levers',
    type: 'text',
    title: 'The Two Levers',
    subtitle: 'Prompt engineering and context engineering are not in competition',
    body: 'Prompt engineering shapes the current turn — structure, role, constraints, examples, format. Context engineering shapes what else is in the window — what you include, what you exclude, what order, and what gets summarized. Both act on the same attention mechanism. Used together, they compound. Used alone, each hits a ceiling.',
    keyTakeaway: 'Prompt engineering makes each token count. Context engineering decides which tokens get to compete in the first place.',
  },
  {
    id: 'decompose-intro',
    type: 'text',
    title: 'From Dense Spec to Wave Plan',
    subtitle: 'Even a perfectly dense prompt is too much context for one session',
    body: 'Module 1 ended with a dense prompt: "React/Next.js 14 e-commerce SPA · comfort footwear · $80–200 · Stripe · WCAG-AA · LCP<2s." That spec packs every dimension you need to build a real site — 9 channels of constraint in 12 tokens. But nobody builds a real codebase in one LLM call. A session that tries to ingest the whole spec, plus the design system, plus every API, plus every test, plus the deploy config runs straight into the lost-in-the-middle wall by turn 5. The fix is not a denser prompt. The fix is decomposition: let the density stay high, but deliver it to agent sessions that are each scoped to one small concern.',
    keyTakeaway: 'Density answers "what does the model need to know?" Decomposition answers "which model does this slice of work?" You need both.',
  },
  {
    id: 'decompose-wave-plan',
    type: 'component',
    component: 'DecomposeWavePlan3D',
    instructions: 'Live tool embedded below. First principles on the cards; the iframe is the real Decomposition Agent — run an intake, then Run Decompose to see the wave plan.',
  },
  {
    id: 'agent-anatomy',
    type: 'text',
    title: 'Anatomy of an Agent Session',
    subtitle: 'Each wave cell is a bounded, testable unit',
    bullets: [
      { label: 'Small window', desc: '8–32k tokens, never the 200k ceiling. Short by design — no room for lost-in-middle.' },
      { label: 'Pre-loaded constraints', desc: 'Only the spec slice this agent owns. 3–5 hard rules, front- and tail-loaded.' },
      { label: 'Guardrails', desc: 'Input validated against a schema. Output validated against a schema. No free-form handoffs.' },
      { label: 'Tested deliverable', desc: 'The agent does not return text. It returns code that passes a predeclared test suite — or it fails closed.' },
      { label: 'Sealed context', desc: 'No accumulating history. Each agent starts fresh, with only the constraints it needs. Its output goes to the wave store, not into another agent’s chat.' },
    ],
    keyTakeaway: 'An agent session is small, scoped, guarded, tested, and sealed. Anything that looks different is a session to avoid.',
  },
  {
    id: 'tools-and-rag',
    type: 'text',
    title: 'Common Concerns → Tools & RAG',
    subtitle: 'The single source of truth that every agent pulls from, none copies',
    body: 'When ten agents all need to know the same thing — an API schema, a design token palette, a compliance rule, a retry policy — the worst thing you can do is paste it into ten prompts. It bloats each context, drifts out of sync, and makes every agent pay the full governance tax. The right move is to externalize.',
    bullets: [
      { label: 'Tools', desc: 'Callable functions with fixed signatures: validators, deployers, linters, test runners. Every agent calls the same tool; no agent owns the implementation.' },
      { label: 'RAG indices', desc: 'Retrieval for things that update: API specs, policy docs, legal guardrails, org-wide patterns. Agents fetch on-demand, not in every prompt.' },
      { label: 'Scratchpads', desc: 'Durable outputs the wave store holds — specs, ADRs, output schemas. The next wave reads from here, not from a previous agent’s chat.' },
    ],
    keyTakeaway: 'If two agents would carry the same 2k tokens, they shouldn’t. Push it to a tool or index and let the model fetch it — consistent, governed, once.',
  },
  {
    id: 'mono-vs-decomp',
    type: 'component',
    component: 'MonolithicVsDecomposed',
    instructions: "Pick a complexity level. Watch Vibe's constraint recall fall and hallucinations climb; Engineered stays flat because each agent's context never grows past its spec slice.",
  },
  {
    id: 'turn-stack-towers',
    type: 'component',
    component: 'TurnStackTowers3D',
    instructions: 'Drag the turn slider, or hit Play. Watch the left tower climb past the buried constraint while the right stacks stay short with constraints always near the top. Click-drag to rotate.',
  },
  {
    id: 'best-practices',
    type: 'component',
    component: 'BestPracticesPlaybook',
    instructions: 'Ten practices across Tools, RAG, Memory, Context, Prompt, Governance. Click any card to see a before/after and how it reinforces constraints, restricts confabulation, and holds quality.',
  },
  {
    id: 'assessment',
    type: 'assessment',
    instructions: '15 MCQ + 4 diagnostic scenarios. Pass threshold: 80% overall AND 75% on diagnostics.',
  },
  {
    id: 'recap',
    type: 'text',
    title: 'Recap & Bridge to Module 4',
    subtitle: 'You now have the hidden mechanic',
    body: 'Lost-in-the-middle is not a mystery — it is attention budget arithmetic. Once you see it, the fixes write themselves: keep contexts short, pin invariants, prune tool outputs, scope sessions, externalize what is common. The natural conclusion of these practices is decomposition: build not one long session, but many short ones, coordinated by a wave plan with tight inputs and tested outputs. That is exactly where Module 4 begins.',
    keyTakeaway: 'Context hygiene is the prerequisite for agentic systems. Module 4 takes the wave plan and makes it run.',
  },
  {
    id: 'build-framework',
    type: 'component',
    component: 'BuildFrameworkPrompt',
    instructions: 'The take-home artifact. Read the file on the left; the right panel explains what to notice. Copy it, adapt it, commit it at your repo root, and hand it to your orchestrator.',
  },
]
