apiVersion: app.smo.tools.fubotv.net/v1alpha1
kind: Application
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  image: {{image}}
  replicas: 1
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { memory: 128Mi }
  ports:
    - name: http
      containerPort: {{port}}
  healthcheck:
    path: {{healthcheck_path}}
    portName: http
  ingress:
    enabled: true
    host: {{host}}
    path: /
    portName: http
    tls:
      certificateArn: arn:aws:acm:us-east-1:650127479436:certificate/18d4217b-cfa1-4420-8710-269e7cf37f36
