import { useState, useMemo } from "react";

const C = {
  bg: "#0B1120", surface: "#131B2E", border: "#1E293B",
  text: "#E2E8F0", textDim: "#94A3B8", accent: "#3B82F6",
  green: "#22C55E", red: "#EF4444", yellow: "#EAB308",
};

const SECTIONS = [
  { name: "Decomposition Principles", icon: "\u25C7" },
  { name: "Parallelism & Dependencies", icon: "\u2BD8" },
  { name: "Orchestration Strategy", icon: "\u2B21" },
  { name: "Cost Analysis", icon: "\u25CE" },
];

const QUESTIONS = [
  // Section 0: Decomposition Principles
  {
    section: 0,
    q: `The Hello World Weather App has animation, reset, weather fetching, city selection, and layout. A developer puts animation AND reset logic in one component. What principle does this violate, and what's the LLM impact?`,
    options: [
      `DRY \u2014 code is duplicated`,
      `Single Responsibility \u2014 the combined component is too complex for a single LLM prompt to generate reliably, increasing confabulation surface`,
      `YAGNI \u2014 reset is unnecessary`,
      `Open/Closed \u2014 can't extend animation without modifying reset`,
    ],
    answer: 1,
    explanation: `Single Responsibility maps directly to LLM prompt quality. A prompt that asks for both animation logic AND reset state management creates two decision surfaces. The LLM must resolve animation timing, keyframe generation, state reset mechanics, and their interaction \u2014 all in one pass. Separating them means each prompt has a narrow, well-defined scope that minimizes confabulation.`,
  },
  {
    section: 0,
    q: `When decomposing the WeatherService for LLM generation, which granularity produces the most reliable output?`,
    options: [
      `One function: fetchAndDisplayWeather(city) that fetches, parses, and renders`,
      `Three functions: getGridPoint(lat,lon), getForecast(gridUrl), formatWeather(data) \u2014 each generated by a separate prompt`,
      `Five functions: one per HTTP header, URL construction, fetch call, JSON parse, and error handling`,
      `Two functions: fetchWeather(city) and WeatherDisplay(data)`,
    ],
    answer: 1,
    explanation: `Three functions hits the sweet spot. Each maps to a single API contract: getGridPoint resolves coordinates to a grid, getForecast fetches from that grid, formatWeather transforms the response. Each prompt has clear input/output types and a single responsibility. Option (a) is too broad \u2014 the LLM must handle HTTP, parsing, AND rendering. Option (c) is over-decomposed \u2014 individual HTTP concerns aren't meaningful units. Option (d) mixes service logic with UI.`,
  },
  {
    section: 0,
    q: `A team decomposes their app into 20 micro-components for LLM generation. Each component is under 50 lines. What problem are they likely to encounter?`,
    options: [
      `No problem \u2014 smaller is always better for LLM generation`,
      `Interface explosion \u2014 the 20 components need well-defined contracts between them, and the LLM must generate consistent interfaces across separate prompts without a shared type system`,
      `The LLM will refuse to generate such small components`,
      `Compile time will increase significantly`,
    ],
    answer: 1,
    explanation: `Over-decomposition creates an interface consistency problem. If Component A expects \`onReset(void)\` but Component B generates \`onReset(animationId: string)\`, the integration breaks. Each prompt is generated independently, so the LLM has no shared memory of interface contracts across components. The fix: define shared interfaces/types FIRST, then include them in every component prompt as a constraint.`,
  },

  // Section 1: Parallelism & Dependencies
  {
    section: 1,
    q: `The Hello World app has 5 components. AnimationEngine, WeatherService, and CitySelector have no dependencies. ResetController depends on AnimationEngine. LayoutShell depends on all four. What is the minimum number of sequential build waves?`,
    options: [
      `5 \u2014 each component must be built sequentially`,
      `2 \u2014 build everything except LayoutShell first, then LayoutShell`,
      `3 \u2014 Wave 1: AnimationEngine+WeatherService+CitySelector, Wave 2: ResetController, Wave 3: LayoutShell`,
      `1 \u2014 all components can be built in parallel with proper interface definitions`,
    ],
    answer: 2,
    explanation: `The dependency graph dictates: Wave 1 builds all independent components in parallel (AnimationEngine, WeatherService, CitySelector). Wave 2 builds ResetController (needs AnimationEngine's API). Wave 3 builds LayoutShell (needs all components). You can't collapse to 2 waves because ResetController must know AnimationEngine's interface before it can be generated. Parallel time: max(30,45,20)+15+25 = 85s vs serial 135s.`,
  },
  {
    section: 1,
    q: `Two components both need a shared TypeScript type: \`type WeatherData = { temp: number; description: string; icon: string }\`. How should this be handled for parallel LLM generation?`,
    options: [
      `Let each LLM prompt define its own type \u2014 they'll be close enough`,
      `Define the shared type in a separate file FIRST, then include it as a constraint in both component prompts`,
      `Generate one component first, extract its type, then pass it to the second`,
      `Use \`any\` type and fix it later`,
    ],
    answer: 1,
    explanation: `Shared types must be defined before parallel generation. If both prompts independently generate WeatherData, they'll diverge \u2014 one might use \`temperature\` vs \`temp\`, or add extra fields. By defining the type upfront and including it in both prompts, the LLM treats it as a grounded constraint. This is the "interface-first" pattern: define contracts, then implement in parallel.`,
  },
  {
    section: 1,
    q: `A build wave completes but WeatherService's output format doesn't match what LayoutShell expects. The team generated them in parallel. What's the root cause?`,
    options: [
      `The LLM is non-deterministic and produced inconsistent outputs`,
      `The prompts for WeatherService and LayoutShell didn't share a common interface specification \u2014 each resolved the data shape independently, causing confabulation divergence`,
      `Parallel generation is inherently unreliable`,
      `WeatherService should have been built first`,
    ],
    answer: 1,
    explanation: `When two prompts independently resolve the same dimension (data shape), they confabulate different solutions. WeatherService might return \`{temp, desc, icon}\` while LayoutShell expects \`{temperature, description, iconUrl}\`. The fix isn't serial generation \u2014 it's including shared interface contracts in both prompts. Parallel generation works perfectly when shared interfaces are pre-defined constraints, not independently resolved dimensions.`,
  },

  // Section 2: Orchestration Strategy
  {
    section: 2,
    q: `When building the Hello World app, should you use orchestrated multi-step generation or a single prompt? What determines the answer?`,
    options: [
      `Always use orchestration \u2014 it's always better`,
      `Use single prompt for apps under 100 lines, orchestration for larger \u2014 the decision is purely about size`,
      `Use orchestration when the app has multiple components with dependencies and the quality cost of confabulation outweighs the time/money cost of multiple prompts`,
      `Use single prompt because orchestration is too complex to set up`,
    ],
    answer: 2,
    explanation: `The decision isn't about size \u2014 it's about confabulation surface. A 200-line app with one concern (pure animation) might work fine as a single prompt. The Hello World app with 5 concerns (animation, reset, weather API, city selection, layout) has multiple dimensions the LLM must resolve. Orchestration resolves each in isolation, reducing the total confabulation surface. The tradeoff: orchestration costs more tokens and takes more time, so use it when quality matters more than speed.`,
  },
  {
    section: 2,
    q: `An orchestrated build of the Hello World app's WeatherService produces a function that calls \`fetch('https://api.weather.gov/...')\` but hardcodes the User-Agent as \`'Mozilla/5.0'\` instead of the required custom string. What went wrong?`,
    options: [
      `The LLM doesn't know about User-Agent requirements`,
      `The orchestration step's prompt specified the API endpoint but left the authentication method as an unresolved dimension \u2014 the LLM defaulted to the most common User-Agent from training data`,
      `api.weather.gov changed its requirements`,
      `The fetch API doesn't support custom User-Agent headers`,
    ],
    answer: 1,
    explanation: `The prompt resolved the API endpoint (grounded) but not the authentication method (unresolved). api.weather.gov requires a custom User-Agent string, but the model's training data overwhelmingly contains Mozilla/5.0 as the default User-Agent. The fix: the prompt must specify "Set header User-Agent: 'HowLLMsWork/1.0 (educational)'" as an explicit constraint. Every HTTP detail that deviates from the training default must be explicitly resolved.`,
  },
  {
    section: 2,
    q: `A team uses 3-step orchestration for their Hello World app. Step 1 generates the frontend. Step 2 generates the API integration. Step 3 generates the layout. Each step independently scores 95%+ grounding. But the integrated app doesn't work. Why?`,
    options: [
      `95% grounding isn't enough \u2014 they need 100%`,
      `Cross-step interface assumptions were not coordinated \u2014 each step grounded against its OWN prompt but the prompts didn't share interface contracts, so Step 1's output API doesn't match Step 2's expected input format`,
      `Orchestration always produces integration bugs`,
      `They needed more steps`,
    ],
    answer: 1,
    explanation: `Per-step grounding measures how well each output matches its prompt \u2014 NOT how well the outputs integrate with each other. If Step 1's prompt says "export a WeatherDisplay component" but Step 3 imports "WeatherWidget", the integration fails despite both being individually well-grounded. Orchestration requires explicit interface contracts shared across steps, or an integration validation step that checks cross-component compatibility.`,
  },

  // Section 3: Cost Analysis
  {
    section: 3,
    q: `Building the Hello World app with dense orchestrated prompts costs $0.047 (5 steps). A single vague prompt costs $0.012. When is the 4x cost justified?`,
    options: [
      `Never \u2014 always minimize cost`,
      `When the $0.035 difference is less than the cost of debugging and fixing the confabulated output from the vague prompt \u2014 typically true for any app that will be deployed to production`,
      `Only for enterprise applications`,
      `When the team has unlimited budget`,
    ],
    answer: 1,
    explanation: `The $0.012 "savings" is illusory if the vague prompt produces code that needs 30 minutes of debugging. At $50/hr engineer time, 30 minutes = $25 \u2014 making the vague approach 500x more expensive in real terms. Dense orchestration eliminates most debugging by resolving dimensions upfront. The break-even point is roughly: if you'd spend more than 2 minutes debugging, the orchestrated approach is cheaper.`,
  },
  {
    section: 3,
    q: `A team's LLM build costs doubled after adding the WeatherService component. Token breakdown shows 420 input + 1,800 output tokens. What optimization should they investigate first?`,
    options: [
      `Switch to a cheaper model`,
      `The 4.3:1 output-to-input ratio suggests the prompt is under-specified \u2014 the LLM is generating excessive output (boilerplate, comments, alternative implementations) because the prompt doesn't constrain the output format. Adding "Return only the function body, no comments, no alternatives" could cut output tokens by 60%+`,
      `Remove the WeatherService feature`,
      `Cache the LLM responses`,
    ],
    answer: 1,
    explanation: `A healthy output-to-input ratio for code generation is 1:1 to 2:1. The 4.3:1 ratio signals the LLM is generating unrequested content \u2014 typically comments explaining the code, alternative approaches, error handling patterns not asked for, and wrapper boilerplate. Dense prompts with explicit output constraints ("return only the async function, TypeScript, no JSDoc") dramatically reduce output tokens. This is the cheapest optimization because it costs zero \u2014 you just improve the prompt.`,
  },
  {
    section: 3,
    q: `A monitoring dashboard shows that 40% of LLM API costs come from retries \u2014 prompts that failed validation and were re-sent. What does this indicate about the prompt strategy?`,
    options: [
      `The LLM model is unreliable and should be switched`,
      `The validation is too strict and should be relaxed`,
      `The prompts have high confabulation surface \u2014 unresolved dimensions cause the LLM to generate output that fails validation, requiring retries. Investing in denser prompts would reduce retry rate and cut total costs by up to 40%`,
      `Retries are normal and expected \u2014 40% is acceptable`,
    ],
    answer: 2,
    explanation: `High retry rates are a direct symptom of under-specified prompts. When the LLM confabulates (fills unresolved dimensions from training data), the output often fails type checking, linting, or functional validation. Each retry costs the full token price again. Dense prompts with all dimensions resolved produce correct output on the first attempt. The ROI of prompt engineering is: (current retry cost) \u00d7 (retry reduction rate). At 40% retry costs, even a 50% reduction in retries saves 20% of the total budget.`,
  },
];

function hashCode(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

function IntroScreen({ onStart, name, setName }) {
  return (
    <div style={{ maxWidth: 600, margin: "0 auto", padding: "60px 40px", textAlign: "center" }}>
      <div style={{ fontSize: 48, marginBottom: 16 }}>{"\u25CE"}</div>
      <h2 style={{ color: C.text, fontSize: 28, marginBottom: 8 }}>Engineering Professional Assessment</h2>
      <p style={{ color: C.accent, fontSize: 16, marginBottom: 24 }}>Building with LLMs</p>
      <p style={{ color: C.textDim, fontSize: 14, marginBottom: 32, lineHeight: 1.6 }}>
        12 questions across 4 sections testing your ability to decompose applications,
        manage parallel generation, orchestrate multi-step builds, and analyze costs.
        Pass threshold: 9/12 (75%).
      </p>
      <input value={name} onChange={e => setName(e.target.value)}
        placeholder="Your name (for certificate)"
        style={{ width: "100%", maxWidth: 300, padding: "10px 14px", background: C.surface,
          border: `1px solid ${C.border}`, borderRadius: 6, color: C.text, fontSize: 14,
          marginBottom: 16, outline: "none", textAlign: "center" }}
      />
      <br />
      <button onClick={onStart} disabled={!name.trim()}
        style={{ background: C.accent, color: "#fff", border: "none", padding: "12px 32px",
          borderRadius: 6, fontSize: 15, cursor: name.trim() ? "pointer" : "default",
          opacity: name.trim() ? 1 : 0.5 }}>
        Begin Assessment
      </button>
    </div>
  );
}

function SectionHeader({ section }) {
  return (
    <div style={{ maxWidth: 600, margin: "0 auto", padding: "60px 40px", textAlign: "center" }}>
      <div style={{ fontSize: 48, marginBottom: 16 }}>{section.icon}</div>
      <h2 style={{ color: C.text, fontSize: 24 }}>Section: {section.name}</h2>
      <p style={{ color: C.textDim, fontSize: 14, marginTop: 8 }}>3 questions</p>
    </div>
  );
}

function QuestionScreen({ q, qNum, total, selected, setSelected, revealed, onReveal, onNext }) {
  return (
    <div style={{ maxWidth: 750, margin: "0 auto", padding: "20px 30px" }}>
      <div style={{ color: C.textDim, fontSize: 12, marginBottom: 8 }}>
        Question {qNum} of {total}
      </div>
      <p style={{ color: C.text, fontSize: 16, lineHeight: 1.6, marginBottom: 20 }}>{q.q}</p>

      <div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>
        {q.options.map((opt, i) => {
          let bg = C.surface;
          let borderColor = C.border;
          if (revealed) {
            if (i === q.answer) { bg = `${C.green}15`; borderColor = C.green; }
            else if (i === selected && i !== q.answer) { bg = `${C.red}15`; borderColor = C.red; }
          } else if (i === selected) {
            bg = `${C.accent}15`; borderColor = C.accent;
          }

          return (
            <div key={i} onClick={() => !revealed && setSelected(i)}
              style={{
                background: bg, border: `1px solid ${borderColor}`, borderRadius: 6,
                padding: "12px 16px", cursor: revealed ? "default" : "pointer",
                transition: "all 0.2s",
              }}>
              <span style={{ color: C.text, fontSize: 14, lineHeight: 1.5 }}>{opt}</span>
            </div>
          );
        })}
      </div>

      {!revealed && selected !== null && (
        <button onClick={onReveal}
          style={{ background: C.accent, color: "#fff", border: "none", padding: "10px 24px",
            borderRadius: 6, cursor: "pointer", fontSize: 14 }}>
          Reveal Answer
        </button>
      )}

      {revealed && (
        <div style={{ marginTop: 16 }}>
          <div style={{
            background: selected === q.answer ? `${C.green}10` : `${C.red}10`,
            border: `1px solid ${selected === q.answer ? C.green : C.red}33`,
            borderRadius: 6, padding: "12px 16px", marginBottom: 16,
          }}>
            <p style={{ color: selected === q.answer ? C.green : C.red, fontSize: 13, margin: "0 0 4px",
              fontWeight: 600 }}>
              {selected === q.answer ? "Correct!" : "Incorrect"}
            </p>
            <p style={{ color: C.textDim, fontSize: 13, margin: 0, lineHeight: 1.5 }}>
              {q.explanation}
            </p>
          </div>
          <button onClick={onNext}
            style={{ background: C.accent, color: "#fff", border: "none", padding: "10px 24px",
              borderRadius: 6, cursor: "pointer", fontSize: 14 }}>
            Next
          </button>
        </div>
      )}
    </div>
  );
}

async function downloadCertPDF({ title, subtitle, name, body, fields, watermark = "LLM ENGINEERING COURSE" }) {
  if (!window.jspdf) { await new Promise((resolve, reject) => { const s = document.createElement("script"); s.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js"; s.onload = resolve; s.onerror = reject; document.head.appendChild(s); }); }
  const { jsPDF } = window.jspdf; const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" }); const W = 297, H = 210;
  doc.setFillColor(15,23,42); doc.rect(0,0,W,H,"F");
  doc.setTextColor(30,41,59); doc.setFontSize(28); doc.setFont("helvetica","bold");
  for (let y = -50; y < H+50; y += 40) for (let x = -100; x < W+100; x += 160) doc.text(watermark, x, y, { angle: 30 });
  doc.setDrawColor(232,168,56); doc.setLineWidth(0.5); doc.rect(12,12,W-24,H-24); doc.rect(15,15,W-30,H-30);
  [[18,18,1,1],[W-18,18,-1,1],[18,H-18,1,-1],[W-18,H-18,-1,-1]].forEach(([x,y,dx,dy])=>{doc.line(x,y,x+8*dx,y);doc.line(x,y,x,y+8*dy);});
  doc.setTextColor(232,168,56); doc.setFontSize(10); doc.setFont("helvetica","bold"); doc.text(title.toUpperCase(), W/2, 38, { align: "center" });
  doc.setTextColor(138,150,167); doc.setFontSize(8); doc.setFont("helvetica","normal"); doc.text(subtitle.toUpperCase(), W/2, 45, { align: "center" });
  doc.setTextColor(138,150,167); doc.setFontSize(10); doc.text("This certifies that", W/2, 60, { align: "center" });
  doc.setTextColor(226,232,240); doc.setFontSize(28); doc.setFont("helvetica","bold"); doc.text(name, W/2, 75, { align: "center" });
  doc.setDrawColor(232,168,56); doc.setLineWidth(0.3); doc.line(W/2-20,82,W/2+20,82);
  doc.setTextColor(138,150,167); doc.setFontSize(9); doc.setFont("helvetica","normal"); doc.text(doc.splitTextToSize(body,180), W/2, 92, { align: "center", lineHeightFactor: 1.6 });
  const fY=135, fS=W/(fields.length+1); fields.forEach((f,i)=>{const x=fS*(i+1); doc.setTextColor(74,85,104); doc.setFontSize(7); doc.setFont("helvetica","bold"); doc.text(f.label.toUpperCase(),x,fY,{align:"center"}); doc.setTextColor(226,232,240); doc.setFontSize(11); doc.text(f.value,x,fY+7,{align:"center"});});
  doc.setTextColor(50,60,80); doc.setFontSize(7); doc.setFont("helvetica","normal"); doc.text("This certificate was generated as part of the LLM Engineering Course", W/2, H-20, { align: "center" });
  doc.save(`${name.replace(/\s+/g,"_")}_Certificate.pdf`);
}

function Certificate({ name, score, total, sectionScores }) {
  const pct = Math.round((score / total) * 100);
  const passed = score >= 9;
  const tier = pct >= 92 ? "Distinction" : pct >= 75 ? "Pass" : "Below Threshold";
  const id = `BLLM-${hashCode(name + score)}-${Date.now().toString(36).toUpperCase()}`;

  return (
    <div style={{ maxWidth: 700, margin: "0 auto", padding: "40px 30px" }}>
      <div style={{
        background: C.surface, border: `2px solid ${passed ? C.green : C.red}`,
        borderRadius: 12, padding: "40px 32px", textAlign: "center",
      }}>
        <div style={{ fontSize: 36, marginBottom: 8 }}>{passed ? "\u25C7" : "\u25CE"}</div>
        <h2 style={{ color: C.text, fontSize: 24, marginBottom: 4 }}>
          {passed ? "Certificate of Completion" : "Assessment Result"}
        </h2>
        <p style={{ color: C.accent, fontSize: 14, marginBottom: 24 }}>
          Engineering Professional — Building with LLMs
        </p>

        <p style={{ color: C.text, fontSize: 20, fontWeight: 600, marginBottom: 4 }}>{name}</p>
        <p style={{ color: C.textDim, fontSize: 14, marginBottom: 24 }}>
          Score: {score}/{total} ({pct}%) — {tier}
        </p>

        {/* Section breakdown */}
        <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 24 }}>
          <thead>
            <tr>
              <th style={{ textAlign: "left", padding: "6px 12px", color: C.textDim, fontSize: 12,
                borderBottom: `1px solid ${C.border}` }}>Section</th>
              <th style={{ textAlign: "right", padding: "6px 12px", color: C.textDim, fontSize: 12,
                borderBottom: `1px solid ${C.border}` }}>Score</th>
            </tr>
          </thead>
          <tbody>
            {SECTIONS.map((sec, i) => (
              <tr key={i}>
                <td style={{ padding: "6px 12px", color: C.text, fontSize: 13,
                  borderBottom: `1px solid ${C.border}` }}>
                  {sec.icon} {sec.name}
                </td>
                <td style={{ padding: "6px 12px", color: C.text, fontSize: 13, textAlign: "right",
                  borderBottom: `1px solid ${C.border}` }}>
                  {sectionScores[i]}/3
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <p style={{ color: C.textDim, fontSize: 11 }}>Certificate ID: {id}</p>
        <p style={{ color: C.textDim, fontSize: 11 }}>
          How to Build with LLMs — {new Date().toLocaleDateString()}
        </p>
      </div>

      <div style={{ textAlign: "center", marginTop: 16 }}>
        <button onClick={() => downloadCertPDF({ title: "Certificate of Comprehension", subtitle: "Building with LLMs", name, body: "has demonstrated comprehension of LLM-driven decomposition, orchestration patterns, parallelism strategies, and costing analysis for building software with large language models.", fields: [{ label: "Score", value: `${score} / ${total}` }, { label: "Percentage", value: `${pct}%` }, { label: "Result", value: tier }, { label: "Date", value: new Date().toLocaleDateString() }, { label: "Certificate ID", value: id }] })}
          style={{ background: "none", color: C.textDim, border: `1px solid ${C.border}`,
            padding: "8px 16px", borderRadius: 6, cursor: "pointer", fontSize: 13 }}>
          Download PDF
        </button>
      </div>
    </div>
  );
}

export default function BuildingQuiz() {
  const [phase, setPhase] = useState("intro");
  const [name, setName] = useState("");
  const [seqIdx, setSeqIdx] = useState(0);
  const [answers, setAnswers] = useState({});
  const [selected, setSelected] = useState(null);
  const [revealed, setRevealed] = useState(false);

  const sequence = useMemo(() => {
    const seq = [];
    for (let s = 0; s < SECTIONS.length; s++) {
      seq.push({ type: "section", section: s });
      QUESTIONS.filter(q => q.section === s).forEach((q) => {
        const indices = q.options.map((_, i) => i);
        for (let i = indices.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [indices[i], indices[j]] = [indices[j], indices[i]];
        }
        seq.push({
          type: "question",
          question: { ...q, options: indices.map(i => q.options[i]), answer: indices.indexOf(q.answer) },
          globalIdx: QUESTIONS.indexOf(q),
        });
      });
    }
    return seq;
  }, []);

  const current = sequence[seqIdx];

  const handleNext = () => {
    if (current?.type === "question" && selected !== null) {
      setAnswers(prev => ({ ...prev, [current.globalIdx]: selected }));
    }
    setSelected(null);
    setRevealed(false);
    if (seqIdx < sequence.length - 1) {
      setSeqIdx(seqIdx + 1);
    } else {
      setPhase("done");
    }
  };

  if (phase === "intro") {
    return <IntroScreen onStart={() => setPhase("sequence")} name={name} setName={setName} />;
  }

  if (phase === "done") {
    const questionSteps = sequence.filter(s => s.type === "question");
    const score = questionSteps.reduce((s, step) => s + (answers[step.globalIdx] === step.question.answer ? 1 : 0), 0);
    const sectionScores = SECTIONS.map((_, si) =>
      questionSteps.filter(step => step.question.section === si)
        .reduce((s, step) => s + (answers[step.globalIdx] === step.question.answer ? 1 : 0), 0)
    );
    return <Certificate name={name} score={score} total={QUESTIONS.length} sectionScores={sectionScores} />;
  }

  if (current.type === "section") {
    return (
      <div>
        <SectionHeader section={SECTIONS[current.section]} />
        <div style={{ textAlign: "center" }}>
          <button onClick={handleNext}
            style={{ background: C.accent, color: "#fff", border: "none", padding: "10px 24px",
              borderRadius: 6, cursor: "pointer", fontSize: 14 }}>
            Start Section
          </button>
        </div>
      </div>
    );
  }

  const qNum = Object.keys(answers).length + 1;

  return (
    <QuestionScreen
      q={current.question}
      qNum={qNum}
      total={QUESTIONS.length}
      selected={selected}
      setSelected={setSelected}
      revealed={revealed}
      onReveal={() => setRevealed(true)}
      onNext={handleNext}
    />
  );
}
